apiVersion: v1
kind: Service
metadata:
  name: email
  namespace: suneasy-dev
  labels:
    app: email
    component: backend
spec:
  type: ClusterIP
  selector:
    app: email
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
