apiVersion: v1
kind: Service
metadata:
  name: log
  namespace: suneasy-dev
  labels:
    app: log
    component: backend
spec:
  type: ClusterIP
  selector:
    app: log
  ports:
  - name: http
    protocol: TCP
    port: 8100
    targetPort: 80
