apiVersion: v1
kind: Service
metadata:
  name: media
  namespace: suneasy-dev
  labels:
    app: media
    component: backend
spec:
  type: ClusterIP
  selector:
    app: media
  ports:
  - name: http
    protocol: TCP
    port: 8060
    targetPort: 80
