apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: suneasy-dev
  labels:
    app: notification
    component: backend
spec:
  type: ClusterIP
  selector:
    app: notification
  ports:
  - name: http
    protocol: TCP
    port: 8070
    targetPort: 80
