apiVersion: v1
kind: Service
metadata:
  name: organization
  namespace: suneasy-dev
  labels:
    app: organization
    component: backend
spec:
  type: ClusterIP
  selector:
    app: organization
  ports:
  - name: http
    protocol: TCP
    port: 8020
    targetPort: 80
