apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: suneasy-dev
  labels:
    app: payment
    component: backend
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
  - name: http
    protocol: TCP
    port: 8050
    targetPort: 80
