apiVersion: v1
kind: Service
metadata:
  name: reservation
  namespace: suneasy-dev
  labels:
    app: reservation
    component: backend
spec:
  type: ClusterIP
  selector:
    app: reservation
  ports:
  - name: http
    protocol: TCP
    port: 8040
    targetPort: 80
