apiVersion: v1
kind: Service
metadata:
  name: resource
  namespace: suneasy-dev
  labels:
    app: resource
    component: backend
spec:
  type: ClusterIP
  selector:
    app: resource
  ports:
  - name: http
    protocol: TCP
    port: 8030
    targetPort: 80
