apiVersion: v1
kind: Service
metadata:
  name: review
  namespace: suneasy-dev
  labels:
    app: review
    component: backend
spec:
  type: ClusterIP
  selector:
    app: review
  ports:
  - name: http
    protocol: TCP
    port: 8120
    targetPort: 80
