apiVersion: v1
kind: Service
metadata:
  name: sms
  namespace: suneasy-dev
  labels:
    app: sms
    component: backend
spec:
  type: ClusterIP
  selector:
    app: sms
  ports:
  - name: http
    protocol: TCP
    port: 8110
    targetPort: 80
