apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: suneasy-dev
  labels:
    app: admin
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 4100
      targetPort: 4100
      name: http
