apiVersion: v1
kind: Service
metadata:
  name: business
  namespace: suneasy-dev
  labels:
    app: business
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: business
  ports:
    - protocol: TCP
      port: 4201
      targetPort: 4201
      name: http
