apiVersion: v1
kind: Service
metadata:
  name: client-web
  namespace: suneasy-dev
  labels:
    app: client-web
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: client-web
  ports:
    - protocol: TCP
      port: 4500
      targetPort: 4500
      name: http
