apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  namespace: suneasy-dev
  labels:
    app: landing
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
        component: frontend
    spec:
      containers:
        - name: landing
          image: suneasy/landing:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4300
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: API_URL
            - name: WS_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: WS_URL
            - name: NODE_ENV
              value: 'development'
          resources:
            requests:
              memory: '1Gi'
              cpu: '100m'
            limits:
              memory: '4Gi'
              cpu: '1000m'
