apiVersion: v1
kind: Service
metadata:
  name: landing
  namespace: suneasy-dev
  labels:
    app: landing
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: landing
  ports:
    - protocol: TCP
      port: 4300
      targetPort: 4300
      name: http
